// <auto-generated />
using System;
using ConferenceRoomBookingAPIv3.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ConferenceRoomBookingAPIv3.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260828120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ConferenceRoomBookingAPIv3.DomainModels.Booking", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("EndsAt")
                    .HasColumnType("datetimeoffset");

                b.Property<decimal>("RoomCost")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("RoomId")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("ServicesCost")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTimeOffset>("StartsAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.ToTable("Bookings");
            });

            modelBuilder.Entity("ConferenceRoomBookingAPIv3.DomainModels.ConferenceRoom", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("BaseHourlyRate")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("Rooms");
            });

            modelBuilder.Entity("ConferenceRoomBookingAPIv3.DomainModels.RoomService", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ConferenceRoomId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("ConferenceRoomId", "Name")
                    .IsUnique();

                b.ToTable("RoomServices");
            });

            modelBuilder.Entity("BookingServices", b =>
            {
                b.Property<Guid>("BookingId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ServiceId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("BookingId", "ServiceId");

                b.HasIndex("ServiceId");

                b.ToTable("BookingServices");
            });

            modelBuilder.Entity("ConferenceRoomBookingAPIv3.DomainModels.Booking", b =>
            {
                b.HasOne("ConferenceRoomBookingAPIv3.DomainModels.ConferenceRoom", null)
                    .WithMany()
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("ConferenceRoomBookingAPIv3.DomainModels.RoomService", b =>
            {
                b.HasOne("ConferenceRoomBookingAPIv3.DomainModels.ConferenceRoom", null)
                    .WithMany("Services")
                    .HasForeignKey("ConferenceRoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("BookingServices", b =>
            {
                b.HasOne("ConferenceRoomBookingAPIv3.DomainModels.Booking", null)
                    .WithMany()
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ConferenceRoomBookingAPIv3.DomainModels.RoomService", null)
                    .WithMany()
                    .HasForeignKey("ServiceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("ConferenceRoomBookingAPIv3.DomainModels.ConferenceRoom", b =>
            {
                b.Navigation("Services");
            });
        }
    }
}
